src/Entity/Adherent.php
<?php

namespace App\Entity;

use App\Helper\StringHelper;
use App\Repository\AdherentRepository;
use App\ValueObject\Address;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: AdherentRepository::class)]
class Adherent
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ORM\Column(type: 'string', length: 55)]
    #[Assert\NotBlank]
    private ?string $firstName = null;

    #[ORM\Column(type: 'string', length: 55)]
    #[Assert\NotBlank]
    private ?string $lastName = null;

    #[ORM\Column(type: 'string', length: 55)]
    #[Assert\NotNull]
    private ?string $gender = null;

    #[ORM\Column(type: 'datetime')]
    #[Assert\NotNull]
    private ?\DateTime $birthDate = null;

    #[ORM\Column(type: 'string', length: 55, nullable: true)]
    #[Assert\NotBlank]
    #[Assert\Regex('/^[\d\s]{14}$/')]
    private ?string $phone = null;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank]
    #[Assert\Email]
    private ?string $email = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $pseudonym = null;

    #[ORM\Embedded(class: Address::class)]
    #[Assert\NotNull]
    #[Assert\Valid]
    private ?Address $address = null;

    #[ORM\Column(type: 'boolean')]
    private bool $reEnrollmentToNotify = false;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $pictureUrl = null;

    private ?UploadedFile $pictureFile = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;
        if (!empty($firstName)) {
            $this->firstName = StringHelper::capitalizeFirstname($firstName);
        }

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;
        if (!empty($lastName)) {
            $this->lastName = mb_strtoupper($lastName);
        }

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(?string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getBirthDate(): ?\DateTime
    {
        return $this->birthDate;
    }

    public function setBirthDate(?\DateTime $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPseudonym(): ?string
    {
        return $this->pseudonym;
    }

    public function setPseudonym(?string $pseudonym): self
    {
        $this->pseudonym = $pseudonym;

        return $this;
    }

    public function getAddress(): ?Address
    {
        return $this->address;
    }

    public function setAddress(?Address $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function isReEnrollmentToNotify(): bool
    {
        return $this->reEnrollmentToNotify;
    }

    public function setReEnrollmentToNotify(bool $reEnrollmentToNotify): self
    {
        $this->reEnrollmentToNotify = $reEnrollmentToNotify;

        return $this;
    }

    public function getPictureUrl(): ?string
    {
        return $this->pictureUrl;
    }

    public function setPictureUrl(?string $pictureUrl): self
    {
        $this->pictureUrl = $pictureUrl;

        return $this;
    }

    public function getPictureFile(): ?UploadedFile
    {
        return $this->pictureFile;
    }

    public function setPictureFile(?UploadedFile $pictureFile): self
    {
        $this->pictureFile = $pictureFile;

        return $this;
    }

    public function getFullName(): string
    {
        return sprintf('%s %s', $this->firstName, $this->lastName);
    }
}

src/Entity/Payment/AbstractPayment.php
<?php

namespace App\Entity\Payment;

use App\Entity\Adherent;
use App\Entity\Season;
use App\Repository\Payment\PaymentRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PaymentRepository::class)]
#[ORM\InheritanceType(value: 'JOINED')]
#[ORM\DiscriminatorColumn(name: 'type', type: 'string')]
#[ORM\DiscriminatorMap([
    'ancv' => AncvPayment::class,
    'cash' => CashPayment::class,
    'check' => CheckPayment::class,
    'discount' => DiscountPayment::class,
    'hello_asso' => HelloAssoPayment::class,
    'pass' => PassPayment::class,
    'transfer' => TransferPayment::class,
])]
#[ORM\Table(name: 'payment')]
abstract class AbstractPayment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    protected ?int $id = null;

    #[ORM\Column(type: 'datetime')]
    #[Assert\NotNull]
    protected \DateTime $date;

    #[ORM\Column(type: 'float')]
    #[Assert\GreaterThan(0)]
    protected ?float $amount = null;

    #[ORM\Column(type: 'text', nullable: true)]
    protected ?string $comment = null;

    #[ORM\ManyToOne(targetEntity: Adherent::class)]
    #[ORM\JoinColumn(nullable: false, onDelete: 'CASCADE')]
    protected Adherent $adherent;

    #[ORM\ManyToOne(targetEntity: Season::class)]
    #[ORM\JoinColumn(nullable: false)]
    protected Season $season;

    public function __construct(Adherent $adherent, Season $season)
    {
        $this->adherent = $adherent;
        $this->season = $season;
        $this->date = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): \DateTime
    {
        return $this->date;
    }

    public function setDate(\DateTime $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(?float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getAdherent(): Adherent
    {
        return $this->adherent;
    }

    public function getSeason(): Season
    {
        return $this->season;
    }

    abstract public function getPaymentType(): string;
}

src/Entity/Payment/CashPayment.php
<?php

namespace App\Entity\Payment;

use App\Enum\PaymentTypeEnum;
use App\Repository\Payment\CashPaymentRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CashPaymentRepository::class)]
#[ORM\Table(name: 'payment_cash')]
class CashPayment extends AbstractPayment
{
    public function getPaymentType(): string
    {
        return PaymentTypeEnum::CASH;
    }
}

src/Form/DataMapper/Payment/AncvPaymentDataMapper.php
<?php

namespace App\Form\DataMapper\Payment;

use App\Entity\Adherent;
use App\Entity\Payment\AncvPayment;
use App\Entity\Season;
use Symfony\Component\Form\DataMapperInterface;
use Symfony\Component\Form\Exception\TransformationFailedException;

class AncvPaymentDataMapper implements DataMapperInterface
{
    public function __construct(
        protected Adherent $adherent,
        protected Season $season,
    ) {
    }

    /**
     * @param AncvPayment|null $viewData
     */
    public function mapDataToForms($viewData, \Traversable $forms): void
    {
        if (!$viewData instanceof AncvPayment) {
            return;
        }

        $forms = iterator_to_array($forms);

        $forms['amount']->setData($viewData->getAmount());
        $forms['date']->setData($viewData->getDate());
        $forms['comment']->setData($viewData->getComment());
        $forms['number']->setData($viewData->getNumber());
    }

    /**
     * @param AncvPayment|null $viewData
     */
    public function mapFormsToData(\Traversable $forms, &$viewData): void
    {
        $forms = iterator_to_array($forms);

        try {
            if (null === $viewData) {
                $viewData = new AncvPayment($this->adherent, $this->season);
            }

            /** @var float|null $amount */
            $amount = $forms['amount']->getData();
            /** @var \DateTime|null $date */
            $date = $forms['date']->getData();
            /** @var string|null $comment */
            $comment = $forms['comment']->getData();
            /** @var string|null $number */
            $number = $forms['number']->getData();

            $viewData->setAmount($amount);
            $viewData->setComment($comment);
            $viewData->setNumber($number);
            if (null !== $date) {
                $viewData->setDate($date);
            }
        } catch (\Exception $e) {
            throw new TransformationFailedException('Unable to map data for ancv payment', 0, $e);
        }
    }
}

src/Form/DataMapper/Payment/CashPaymentDataMapper.php
<?php

namespace App\Form\DataMapper\Payment;

use App\Entity\Adherent;
use App\Entity\Payment\CashPayment;
use App\Entity\Season;
use Symfony\Component\Form\DataMapperInterface;
use Symfony\Component\Form\Exception\TransformationFailedException;

class CashPaymentDataMapper implements DataMapperInterface
{
    public function __construct(
        protected Adherent $adherent,
        protected Season $season,
    ) {
    }

    /**
     * @param CashPayment|null $viewData
     */
    public function mapDataToForms($viewData, \Traversable $forms): void
    {
        if (!$viewData instanceof CashPayment) {
            return;
        }

        $forms = iterator_to_array($forms);

        $forms['amount']->setData($viewData->getAmount());
        $forms['date']->setData($viewData->getDate());
        $forms['comment']->setData($viewData->getComment());
    }

    /**
     * @param CashPayment|null $viewData
     */
    public function mapFormsToData(\Traversable $forms, &$viewData): void
    {
        $forms = iterator_to_array($forms);

        try {
            if (null === $viewData) {
                $viewData = new CashPayment($this->adherent, $this->season);
            }

            /** @var float|null $amount */
            $amount = $forms['amount']->getData();
            /** @var \DateTime|null $date */
            $date = $forms['date']->getData();
            /** @var string|null $comment */
            $comment = $forms['comment']->getData();

            $viewData->setAmount($amount);
            $viewData->setComment($comment);
            if (null !== $date) {
                $viewData->setDate($date);
            }
        } catch (\Exception $e) {
            throw new TransformationFailedException('Unable to map data for cash payment', 0, $e);
        }
    }
}

src/Form/DataMapper/Payment/CheckPaymentDataMapper.php
<?php

namespace App\Form\DataMapper\Payment;

use App\Entity\Adherent;
use App\Entity\Payment\CheckPayment;
use App\Entity\Season;
use Symfony\Component\Form\DataMapperInterface;
use Symfony\Component\Form\Exception\TransformationFailedException;

class CheckPaymentDataMapper implements DataMapperInterface
{
    public function __construct(
        protected Adherent $adherent,
        protected Season $season,
    ) {
    }

    /**
     * @param CheckPayment|null $viewData
     */
    public function mapDataToForms($viewData, \Traversable $forms): void
    {
        if (!$viewData instanceof CheckPayment) {
            return;
        }

        $forms = iterator_to_array($forms);

        $forms['amount']->setData($viewData->getAmount());
        $forms['date']->setData($viewData->getDate());
        $forms['comment']->setData($viewData->getComment());
        $forms['number']->setData($viewData->getNumber());
        $forms['cashingDate']->setData($viewData->getCashingDate());
    }

    /**
     * @param CheckPayment|null $viewData
     */
    public function mapFormsToData(\Traversable $forms, &$viewData): void
    {
        $forms = iterator_to_array($forms);

        try {
            if (null === $viewData) {
                $viewData = new CheckPayment($this->adherent, $this->season);
            }

            /** @var float|null $amount */
            $amount = $forms['amount']->getData();
            /** @var \DateTime|null $date */
            $date = $forms['date']->getData();
            /** @var string|null $comment */
            $comment = $forms['comment']->getData();
            /** @var string|null $number */
            $number = $forms['number']->getData();
            /** @var \DateTime|null $cashingDate */
            $cashingDate = $forms['cashingDate']->getData();

            $viewData->setAmount($amount);
            $viewData->setComment($comment);
            $viewData->setNumber($number);
            $viewData->setCashingDate($cashingDate);
            if (null !== $date) {
                $viewData->setDate($date);
            }
        } catch (\Exception $e) {
            throw new TransformationFailedException('Unable to map data for check payment', 0, $e);
        }
    }
}

src/Form/DataMapper/Payment/DiscountPaymentDataMapper.php
<?php

namespace App\Form\DataMapper\Payment;

use App\Entity\Adherent;
use App\Entity\Payment\DiscountPayment;
use App\Entity\Season;
use Symfony\Component\Form\DataMapperInterface;
use Symfony\Component\Form\Exception\TransformationFailedException;

class DiscountPaymentDataMapper implements DataMapperInterface
{
    public function __construct(
        protected Adherent $adherent,
        protected Season $season,
    ) {
    }

    /**
     * @param DiscountPayment|null $viewData
     */
    public function mapDataToForms($viewData, \Traversable $forms): void
    {
        if (!$viewData instanceof DiscountPayment) {
            return;
        }

        $forms = iterator_to_array($forms);

        $forms['amount']->setData($viewData->getAmount());
        $forms['date']->setData($viewData->getDate());
        $forms['comment']->setData($viewData->getComment());
        $forms['discount']->setData($viewData->getDiscount());
    }

    /**
     * @param DiscountPayment|null $viewData
     */
    public function mapFormsToData(\Traversable $forms, &$viewData): void
    {
        $forms = iterator_to_array($forms);

        try {
            if (null === $viewData) {
                $viewData = new DiscountPayment($this->adherent, $this->season);
            }

            /** @var float|null $amount */
            $amount = $forms['amount']->getData();
            /** @var \DateTime|null $date */
            $date = $forms['date']->getData();
            /** @var string|null $comment */
            $comment = $forms['comment']->getData();
            /** @var string|null $discount */
            $discount = $forms['discount']->getData();

            $viewData->setAmount($amount);
            $viewData->setComment($comment);
            $viewData->setDiscount($discount);
            if (null !== $date) {
                $viewData->setDate($date);
            }
        } catch (\Exception $e) {
            throw new TransformationFailedException('Unable to map data for discount payment', 0, $e);
        }
    }
}

src/Form/DataMapper/Payment/HelloAssoPaymentDataMapper.php
<?php

namespace App\Form\DataMapper\Payment;

use App\Entity\Adherent;
use App\Entity\Payment\HelloAssoPayment;
use App\Entity\Season;
use Symfony\Component\Form\DataMapperInterface;
use Symfony\Component\Form\Exception\TransformationFailedException;

class HelloAssoPaymentDataMapper implements DataMapperInterface
{
    public function __construct(
        protected Adherent $adherent,
        protected Season $season,
    ) {
    }

    /**
     * @param HelloAssoPayment|null $viewData
     */
    public function mapDataToForms($viewData, \Traversable $forms): void
    {
        if (!$viewData instanceof HelloAssoPayment) {
            return;
        }

        $forms = iterator_to_array($forms);

        $forms['amount']->setData($viewData->getAmount());
        $forms['date']->setData($viewData->getDate());
        $forms['comment']->setData($viewData->getComment());
    }

    /**
     * @param HelloAssoPayment|null $viewData
     */
    public function mapFormsToData(\Traversable $forms, &$viewData): void
    {
        $forms = iterator_to_array($forms);

        try {
            if (null === $viewData) {
                $viewData = new HelloAssoPayment($this->adherent, $this->season);
            }

            /** @var float|null $amount */
            $amount = $forms['amount']->getData();
            /** @var \DateTime|null $date */
            $date = $forms['date']->getData();
            /** @var string|null $comment */
            $comment = $forms['comment']->getData();

            $viewData->setAmount($amount);
            $viewData->setComment($comment);
            if (null !== $date) {
                $viewData->setDate($date);
            }
        } catch (\Exception $e) {
            throw new TransformationFailedException('Unable to map data for Hello Asso payment', 0, $e);
        }
    }
}

templates/back/payment/_form.html.twig
{% block ancv_payment_row %}
  <div class="columns">
    <div class="column">{{ form_row(form.amount) }}</div>
    <div class="column">{{ form_row(form.date) }}</div>
  </div>
  <div class="columns">
    <div class="column">{{ form_row(form.number) }}</div>
  </div>
  <div class="columns">
    <div class="column">{{ form_row(form.comment) }}</div>
  </div>
{% endblock %}

{% block cash_payment_row %}
  <div class="columns">
    <div class="column">{{ form_row(form.amount) }}</div>
    <div class="column">{{ form_row(form.date) }}</div>
  </div>
  <div class="columns">
    <div class="column">{{ form_row(form.comment) }}</div>
  </div>
{% endblock %}

{% block check_payment_row %}
  <div class="columns">
    <div class="column">{{ form_row(form.amount) }}</div>
    <div class="column">{{ form_row(form.date) }}</div>
  </div>
  <div class="columns">
    <div class="column">{{ form_row(form.number) }}</div>
    <div class="column">{{ form_row(form.cashingDate) }}</div>
  </div>
  <div class="columns">
    <div class="column">{{ form_row(form.comment) }}</div>
  </div>
{% endblock %}

{% block discount_payment_row %}
  <div class="columns">
    <div class="column">{{ form_row(form.amount) }}</div>
    <div class="column">{{ form_row(form.date) }}</div>
  </div>
  <div class="columns">
    <div class="column">{{ form_row(form.discount) }}</div>
  </div>
  <div class="columns">
    <div class="column">{{ form_row(form.comment) }}</div>
  </div>
{% endblock %}

{% block hello_asso_payment_row %}
  <div class="columns">
    <div class="column">{{ form_row(form.amount) }}</div>
    <div class="column">{{ form_row(form.date) }}</div>
  </div>
  <div class="columns">
    <div class="column">{{ form_row(form.comment) }}</div>
  </div>
{% endblock %}

{% block pass_payment_row %}
  <div class="columns">
    <div class="column">{{ form_row(form.amount) }}</div>
    <div class="column">{{ form_row(form.date) }}</div>
  </div>
  <div class="columns">
    <div class="column">{{ form_row(form.number) }}</div>
  </div>
  <div class="columns">
    <div class="column">{{ form_row(form.comment) }}</div>
  </div>
{% endblock %}

{% block transfer_payment_row %}
  <div class="columns">
    <div class="column">{{ form_row(form.amount) }}</div>
    <div class="column">{{ form_row(form.date) }}</div>
  </div>
  <div class="columns">
    <div class="column">{{ form_row(form.label) }}</div>
  </div>
  <div class="columns">
    <div class="column">{{ form_row(form.comment) }}</div>
  </div>
{% endblock %}

templates/back/payment/edit.html.twig
{% extends 'layout/_back.html.twig' %}

{% block body %}

    {% form_theme form 'back/payment/_form.html.twig' %}

    <h1 class="title">{{ 'back.payment.edit.title'|trans }} - {{ ('enum.paymentType.'~payment.paymentType)|trans }}</h1>

    <div class="form-wrapper">
        {{ form_start(form) }}
        {{ form_row(form) }}
        <div class="is-flex is-flex-direction-row is-justify-content-flex-end is-align-content-center">
            <div class="block">
                <a href="{{ backLink }}" class="button is-outlined">{{ 'global.cancel'|trans }}</a>
                <button type="submit" class="button is-primary">{{ 'global.validate'|trans }}</button>
            </div>
        </div>
        {{ form_end(form) }}
    </div>

{% endblock %}

templates/back/payment/list.html.twig
{% extends 'back.html.twig' %}

{% block body %}

    {% include 'back/adherent/_header.html.twig' with {
        'current': 'payments',
        'adherent': adherent,
        'registration': registration,
    } %}

    <h1 class="title">{{ 'back.payment.grid.title'|trans }}</h1>

    <nav class="level">
        <div class="level-left"></div>
        <div class="level-right">
            <p class="level-item">
                <a href="{{ path('bo_payment_new', {'adherent': adherent.id}) }}" class="button is-primary">
                    <span>{{ 'back.payment.grid.action.new'|trans }}</span>
                    <span class="icon is-small">
                        <i class="icon-more"></i>
                    </span>
                </a>
            </p>
        </div>
    </nav>

    {% embed 'back/components/_table.html.twig' %}

        {% block thead %}
            <th>{{ 'back.payment.grid.header.date'|trans }}</th>
            <th>{{ 'back.payment.grid.header.amount'|trans }}</th>
            <th>{{ 'back.payment.grid.header.type'|trans }}</th>
            <th>{{ 'back.payment.grid.header.season'|trans }}</th>
            <th></th>
        {% endblock %}

        {% block tbody %}
            {% for payment in payments %}
                <tr>
                    <td>{{ payment.date|date('d/m/Y') }}</td>
                    <td>{{ payment.amount|number_format(2, ',' , ' ') }}</td>
                    <td>{{ ('enum.paymentType.'~payment.paymentType)|trans }}</td>
                    <td>{{ payment.season.label }}</td>
                    <td class="center">
                        <a href="{{ path('bo_payment_view', {'payment': payment.id}) }}" class="button is-info">
                            <span class="icon"><i class="icon-eye"></i></span>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        {% endblock %}

    {% endembed %}

{% endblock %}

templates/back/payment/list_for_adherent.html.twig
{% extends 'layout/_back.html.twig' %}

{% block body %}

    {% include 'back/adherent/_header.html.twig' with {
        'current': 'payments',
        'adherent': adherent,
        'registration': registration,
    } %}

    <h1 class="title">{{ 'back.payment.grid.title'|trans }}</h1>

    {% if (registration.season.id == currentSeason.id) %}
        {% if not contributionSold %}
            <div class="notification is-warning">
                <div class="is-size-4 mb-2">{{ registration.priceOption.label }} - {{ registration.priceOption.amount }}€</div>
                {{ 'back.payment.grid.info.toPay'|trans({'%year%': currentSeason.getDisplayLabel(), '%amount%': amountToPay}) }}
            </div>
        {% else %}
            <div class="notification is-success">
                <div class="is-size-4 mb-2">{{ registration.priceOption.label }} - {{ registration.priceOption.amount }}€</div>
                {{ 'back.payment.grid.info.isSold'|trans({'%year%': currentSeason.getDisplayLabel()}) }}
            </div>
        {% endif %}
    {% endif %}

    <nav class="level">
        <div class="level-left"></div>
        <div class="level-right">
            <p class="level-item">
                <a href="{{ path('bo_payment_new', {'adherent': adherent.id}) }}" class="button is-primary">
                    <span>{{ 'back.payment.grid.action.new'|trans }}</span>
                    <span class="icon is-small">
                        <i class="icon-more"></i>
                    </span>
                </a>
            </p>
        </div>
    </nav>

    {% embed 'back/components/_table.html.twig' %}

        {% block thead %}
            <th>{{ 'back.payment.grid.header.date'|trans }}</th>
            <th>{{ 'back.payment.grid.header.amount'|trans }}</th>
            <th>{{ 'back.payment.grid.header.type'|trans }}</th>
            <th>{{ 'back.payment.grid.header.season'|trans }}</th>
            <th></th>
        {% endblock %}

        {% block tbody %}
            {% for payment in payments %}
                <tr>
                    <td>{{ payment.date|date('d/m/Y') }}</td>
                    <td>{{ payment.amount|number_format(2, ',' , ' ') }}</td>
                    <td>{{ ('enum.paymentType.'~payment.paymentType)|trans }}</td>
                    <td>{{ payment.season.getDisplayLabel() }}</td>
                    <td class="action">
                        <a href="{{ path('bo_payment_view', {'payment': payment.id}) }}" class="button is-info">
                            <span class="icon"><i class="icon-eye"></i></span>
                        </a>
                        <a href="{{ path('bo_payment_edit', {'payment': payment.id}) }}" class="button is-primary">
                            <span class="icon"><i class="icon-pencil"></i></span>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        {% endblock %}

    {% endembed %}

{% endblock %}

templates/back/payment/list_for_season.html.twig
{% extends 'layout/_back.html.twig' %}

{% block body %}

    <h1 class="title">{{ 'back.payment.grid.title'|trans }}</h1>

    <div class="tabs is-centered is-boxed">
        <ul>
            {% for season in seasons %}
                <li{% if season.id == currentSeason.id %} class="is-active"{% endif %}>
                    <a href="{{ path('bo_payment_list_for_season', {'season': season.id}) }}">{{ season.getDisplayLabel() }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>

    <div data-grid="data-grid">

        <nav class="level">
            <div class="level-left">
                <div class="level-item">
                    <div class="field has-addons">
                        <p class="control has-icons-left">
                            <input
                                id="input-search-id"
                                class="search input"
                                type="text"
                                autofocus="autofocus"
                                placeholder="{{ 'global.search'|trans }}"
                                data-search='["type", "adherent"]'
                            />
                            <span class="icon is-small is-left">
                                <i class="icon-search"></i>
                            </span>
                        </p>
                    </div>
                </div>
            </div>
            <div class="level-right">
                <p class="level-item">
                    <a href="{{ path('bo_export_payment', {'season': currentSeason.id}) }}" target="_blank" class="button is-primary">
                        <span>{{ 'global.export'|trans }}</span>
                        <span class="icon is-small">
                            <i class="icon-export"></i>
                        </span>
                    </a>
                </p>
            </div>
        </nav>

        {% embed 'back/components/_table.html.twig' %}

            {% block thead %}
                <th>
                    {{ 'back.payment.grid.header.date'|trans }}
                    <div class="sort" data-sort="date"></div>
                </th>
                <th>
                    {{ 'back.payment.grid.header.type'|trans }}
                    <div class="sort" data-sort="lastName"></div>
                </th>
                <th>{{ 'back.payment.grid.header.amount'|trans }}</th>
                <th>{{ 'back.payment.grid.header.adherent'|trans }}</th>
                <th></th>
            {% endblock %}

            {% block tbody %}
                {% for payment in payments %}
                    <tr>
                        <td>{{ payment.date|date('d/m/Y') }}</td>
                        <td class="type">{{ ('enum.paymentType.'~payment.paymentType)|trans }}</td>
                        <td>{{ payment.amount|number_format(2, ',' , ' ') }}</td>
                        <td class="adherent">{{ payment.adherent.fullName }}</td>
                        <td class="action">
                            <a href="{{ path('bo_payment_view_for_season', {'payment': payment.id}) }}" class="button is-info">
                                <span class="icon"><i class="icon-eye"></i></span>
                            </a>
                            <a href="{{ path('bo_payment_edit_for_season', {'payment': payment.id}) }}" class="button is-primary">
                                <span class="icon"><i class="icon-pencil"></i></span>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            {% endblock %}

        {% endembed %}

    </div>

{% endblock %}

templates/back/payment/view.html.twig
{% extends 'layout/_back.html.twig' %}

{% block body %}

    {% form_theme form 'back/payment/_form.html.twig' %}

    <nav class="level">
        <div class="level-left"></div>
        <div class="level-right">
            <p class="level-item">
                <a href="{{ backLink }}" class="button is-outlined">
                    <span>{{ 'global.back'|trans }}</span>
                    <span class="icon"><i class="icon-back"></i></span>
                </a>
            </p>
            <p class="level-item">
                <form
                    data-confirm
                    data-confirm-message="{{ 'global.confirmDelete'|trans }}"
                    action="{{ deleteLink }}"
                    method="POST"
                >
                    <input type="hidden" name="_token" value="{{ csrf_token('delete-'~payment.id) }}" />
                    <button type="submit" class="button is-danger">
                        <span>{{ 'global.delete'|trans }}</span>
                        <span class="icon"><i class="icon-cross"></i></span>
                    </button>
                </form>
            </p>
        </div>
    </nav>

    <h1 class="title">{{ 'back.payment.view.title'|trans }} - {{ ('enum.paymentType.'~payment.paymentType)|trans }}</h1>

    {{ form(form) }}

{% endblock %}